# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sh6P6NmjxQRn0ebN-0NOnR8NBfxW2HF_
"""

import streamlit as st
import pandas as pd
import numpy as np

# Title
st.title("🚗 Car Evaluation Predictor")
st.write("Input car features below to predict its evaluation class.")

# Define categorical input options
buying_options = ['vhigh', 'high', 'med', 'low']
maint_options = ['vhigh', 'high', 'med', 'low']
doors_options = ['2', '3', '4', '5more']
persons_options = ['2', '4', 'more']
lug_boot_options = ['small', 'med', 'big']
safety_options = ['low', 'med', 'high']

# User inputs
buying = st.selectbox('Buying Price', buying_options)
maint = st.selectbox('Maintenance Cost', maint_options)
doors = st.selectbox('Number of Doors', doors_options)
persons = st.selectbox('Passenger Capacity', persons_options)
lug_boot = st.selectbox('Luggage Boot Size', lug_boot_options)
safety = st.selectbox('Safety Level', safety_options)

# Convert input to dataframe
input_df = pd.DataFrame({
    'buying': [buying],
    'maint': [maint],
    'doors': [doors],
    'persons': [persons],
    'lug_boot': [lug_boot],
    'safety': [safety]
})

# One-hot encode like training data
input_encoded = pd.get_dummies(input_df)

# Reindex to match training columns
model_features = [
    'buying_high', 'buying_low', 'buying_med', 'buying_vhigh',
    'maint_high', 'maint_low', 'maint_med', 'maint_vhigh',
    'doors_2', 'doors_3', 'doors_4', 'doors_5more',
    'persons_2', 'persons_4', 'persons_more',
    'lug_boot_big', 'lug_boot_med', 'lug_boot_small',
    'safety_high', 'safety_low', 'safety_med']

for col in model_features:
    if col not in input_encoded:
        input_encoded[col] = 0

input_encoded = input_encoded[model_features]

# Scale input
scaled_input = scaler.transform(input_encoded)

# Make prediction
pred = model.predict(scaled_input)[0]
label_mapping = {0: 'unacc', 1: 'acc', 2: 'good', 3: 'vgood'}
predicted_label = label_mapping[pred]

# Display result
st.success(f"Predicted Car Evaluation: **{predicted_label.upper()}**")


st.write("Made by kittu")